### ISSUE TITLE
Some weapons don't function correctly

### ISSUE THREAD

**Issue by GitZurah** [ekknod/EC#44] opened 2023-12-16 15:36 UTC
TEC9, XM1014, SG553, SSG08 and UMP45 aren't working properly, and as such, neither Aimbot nor ESP will work when having those weapons selected

**Comment by fortXIV** [comment] 2023-12-16 18:18
+1

**Comment by kaisersoju** [comment] 2023-12-17 03:53
Did you even read the code?

TEC9 is grouped with pistol. So was SSG08 as commented.
[https://github.com/ekknod/EC/blob/main/cs2/shared/cs.cpp#L941](url)

The code parses out knives, grenades, pistols and snipers. If it's not those then the rest are treated universally as rifles. 
[https://github.com/ekknod/EC/blob/main/cs2/shared/cs.cpp#L975](url)

I have definitely tested out each weapon on an aim map and the aimbot works. I don't like ESP so it's always off for me.

It's a non-issue and recommend #44 closed.

**Comment by GitZurah** [comment] 2023-12-17 09:20
```
/* pistol */
{
	COMPARISON data[] = {
		{"ssg08"}, // scout and deagle, in my opinion definitely belongs to same category
		{"hkp2000"},
		{"deagle"},
		{"p250"},
		{"elite"},
		{"fiveseven"},
		{"glock"},
		{"tec9"},
	};
	for (int i = 0; i < sizeof(data) / sizeof(COMPARISON); i++)
	{
		if (!strcmpi_imp(index, data[i].weapon_name))
		{
			return cs::WEAPON_CLASS::Pistol;
		}
	}
}
```
I read the code, which is why I'm reporting that some weapons don't function properly. P250 and Deagle are in the same class as the Tec9 for example, and the former 2 work yet the latter doesn't.

**Comment by ekknod** [comment] 2023-12-17 09:29
the issue is more likely caused by m_pClippingWeapon. for some reason it doesn't work always for every gun.

**Comment by GitZurah** [comment] 2023-12-17 09:32
> the issue is more likely caused by m_pClippingWeapon. for some reason it doesn't work always for every gun.

guessed so too because the weapon names inside the function are all correct meaning if its in the list it _should_ work just fine

**Comment by kaisersoju** [comment] 2023-12-18 16:00
Bugs as result of Source Engine 2 are out-of-scope. If the code logic is correct then there's nothing to fix. You got your answer. So close the issue.

**Comment by GitZurah** [comment] 2023-12-18 18:56
I'm yet to see another cheat with the same issue, so no, this isn't a universal issue thats simply due to the engine, as there obviously can be ways to mitigate the issue

**Comment by kaisersoju** [comment] 2023-12-18 21:32
You're comparing "another cheat" but that's not really a valid argument. EC is open source code. If another cheat works, do you have it's source code? Or was it closed source? This matters greatly because with another cheat with working source code, you can actually compare and provide meaningful insight rather than waste the developer's time. 

Having open source code is for learning purposes and isn't meant to compete against commercial products. So your point that there's an obvious way to mitigate your problem is very simple: stop using EC and go use this other cheat. EC doesn't need to be better than another cheat. Your ability to learn and contribute to the code base is indicative of whether EC becomes better or not. It's not ekknod's job to chase after every minor bug just because someone posts here. It works on my machine and it works on his. If I can't replicate the issue described then that's also out-of-scope. That's your feedback. Read through most of the issues posted here and on the discord server. Enough of them are not worth the time to answer or deserves a response.

So since you disagree that the issue is not tied to the game engine, then how do you propose to resolve it? I'll start with one proposition. Try as many versions of EC as you can and compare their behaviors. Try another open source cheat. Report your findings here. Try demonstrating how we can replicate the bug. Also, if you think you found the solution, why not try fixing it and testing it out? No copping out that you're not good at coding or whatever excuse. If you're making coding arguments here, you better be delivering the goods. Do some real contributing if you think issue #44 is even relevant.

**Closed** 2023-12-18 21:53 UTC

**Comment by fortXIV** [comment] 2024-02-10 13:38
I see the issue is closed, but i'm using ekknod ESP version from the website. Currently these weapons dont work for me: Glock, m4, mp9, usp and several other guns.

**Comment by GitZurah** [comment] 2024-02-10 14:23
I closed it because no one has found any relevant solution to this issue yet
